version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
     
      - run:
          name: Install dependencies
          command: npm install
      
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'circleci-project-setup' ]; then
              npm run build
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'circleci-project-setup' ]; then
              aws s3 sync build s3://http://aws-sam-cli-managed-default-samclisourcebucket-181dmbhu62xx8.s3-website-us-east-1.amazonaws.com
            fi
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci-project-setup
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - circleci-project-setup
